# This is a basic workflow to help you get started with Actions

name: Creating typescript Indexes
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 🛠️ Build Indexes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: DaanV2/Typescript-Action-Create-Indexes@latest
        with: 
          folder: ${{github.workspace}}/src/Lib

      - name: ✏️ Commit changes
        continue-on-error: true
        run: |
          cd ${{github.workspace}}
          git config --global user.email "orbi@blockception.com"
          git config --global user.name "Orbi-bot"
          git add .
          git commit -m "auto: Generated typescript includes"
          git push
